### ISSUE TITLE
Support more DNS providers

### ISSUE THREAD

**Issue by jsarenik** [spf-tools/spf-tools#109]
There is a request to support Akamai at first.
https://github.com/akamai-open/api-kickstart/blob/master/examples/node/src/dns-zone-management.js

There should be some easy way to make it work. Think about it and propose solutions.

**Comment by jcbf** [comment]
Probably the best way to go is to create a shell script for each provider similar to cloudflare.sh .

**Comment by jsarenik** [comment]
@jcbf It was specific question of my friend, asked via other ephemeral channels. That's why I have made this issue right away to not forget about it.

**Comment by jcbf** [comment]
For reference: @AlexCline just contributed with AWS Route53 support in #141

**Comment by jsarenik** [comment]
This does not seems to be really important. Closing.
