### ISSUE TITLE
mkblocks.sh -l  creates TXT record longer than 255 characters. It COULD split them

### ISSUE THREAD

**Issue by mkearey** [spf-tools/spf-tools#159]
mkblocks.sh -l 350 potentially results in a TXT string longer than the DNS required 255 characters.

It would be a nice feature to be able to split strings as per the DNS 255 char requirement. I will see if I am able to modify it to do what I need and share it.

**Comment by jsarenik** [comment]
The whole set of scripts was started because of the DNS 255 char requirement in SPF. I am wondering, maybe `mkblocks.sh` is already too far in the chain and does not cope with the length...?

**Comment by jsarenik** [comment]
Oops, sorry, I misunderstood the question.

**Comment by jsarenik** [comment]
That's why there is the `-l` parameter. When it is set to length over 255, it will go beyond the limit... Normal setting is 257 (i.e. 255 + two bytes for quotes `""`). Does it make sense?

To me it seems like complaining about the speed of car. When I go 170 MPH I may break the limit of 80 MPH, but then I chose to go 170 in the first place...

**Comment by mkearey** [comment]
I suspect you are not aware of the capability - Its possible to exceed 255 CHARACTERS in an SPF TXT record, the strings cannot exceed 255. This explains it:

https://kb.isc.org/docs/aa-00356


ie you can have a record like so :

IN TXT "v=spf1...<total character length of this quoted string  255>" "continued txt record , total character length of this quoted string 255"


And so on. 

OF COURSE this can also potentially cause the DNS query to exceed 512 bytes and the DNS client will fall back to TCP..

**Comment by jsarenik** [comment]
Aah, I see now. Thank you for explanation. I have not explored these options yet. Do you have any idea or a patch?

**Comment by mkearey** [comment]
I have something rudimentary, I will have it ready  tomorrow :)  My shell scripting is POOR  but its close to working as I want it.  I will share it tomorrow.

**Comment by mkearey** [comment]
Here is what I have SO FAR. The problem I am trying to solve is how to give awk  the $strlength variable value ( instead of hard wired 255)  NOTE I did it this way so as to introduce minimal bugs :) :

diff --git a/mkblocks.sh b/mkblocks.sh
index d5bb53d..9a72b5d 100755
--- a/mkblocks.sh
+++ b/mkblocks.sh
@@ -41,6 +41,7 @@ policy="~all"
 delim="^"
 header="v=spf1"
 length=257
+strlength=255
 start=1
 
 usage() {
@@ -51,6 +52,7 @@ usage() {
        Available options:
          -h HEADER                  set SPF header
          -l LENGTH                  set desired packet length
+         -L STRLENGTH               set desired DNS STRING length
          -p PREFIX                  set SPF prefix
          -x SUFFIX                  set SPF suffix
          -o POLICY                  set default SPF policy
@@ -60,6 +62,7 @@ usage() {
        Default values:
          HEADER = $header
          LENGTH = $length
+         STRLENGTH = $strlength
          PREFIX = $prefix
          SUFFIX = $suffix
          POLICY = $policy
@@ -69,10 +72,11 @@ usage() {
     exit 1
 }
 
-while getopts "h:l:p:x:o:d:s:-" opt; do
+while getopts "h:l:L:p:x:o:d:s:-" opt; do
   case $opt in
     h) test -n "$OPTARG" && header=$OPTARG;;
     l) test -n "$OPTARG" && length=$OPTARG;;
+    L) test -n "$OPTARG" && length=$OPTARG;;
     p) test -n "$OPTARG" && prefix=$OPTARG;;
     x) test -n "$OPTARG" && suffix=$OPTARG;;
     o) test -n "$OPTARG" && policy=$OPTARG;;
@@ -108,7 +112,8 @@ myout() {
   fi
   mystart=$(echo $rrlabel | mysed $((mycounter-1)))
   myrest=$(echo $2 | mysed $((mycounter)))
-  echo ${mystart}${delim}\"$header $myrest\"
+  output=$(echo -n  "$header $myrest" | awk '{gsub(/.{255}/,"&\" \"")}1')
+  echo ${mystart}${delim}\"$output\"
 }

**Comment by jsarenik** [comment]
It's good, though if you want some more recognition, make a new branch and send this as a pull request. See what I have so far: https://github.com/spf-tools/spf-tools/tree/mkearey/255_characters

**Comment by jsarenik** [comment]
@mkearey As for me, spf-tools/spf-tools@5fcfbd9483be45a97c596c1dd9f2888e01d7a0d6 is ready to fly. Do you want to change anything? OK to merge?

**Comment by mkearey** [comment]
Greetings again I don't seem to have permission to push to the branch. So here is my finall patch.
I think there is no need for the ability to set string length on CLI. DNS will always have this 255 limit, and making it shorter has no benefit :)

[final255.txt](https://github.com/spf-tools/spf-tools/files/3454264/final255.txt)

**Comment by jsarenik** [comment]
@mkearey you can always fork and send a pull request. Try it. I want your name in git history.

**Comment by jcbf** [comment]
Just reading the code and not actually testing but,  @jsarenik 
<img width="556" alt="image" src="https://user-images.githubusercontent.com/836049/62320910-5b85c480-b499-11e9-96cb-de46bef459d4.png">
I think you meant :

`    L) test -n "$OPTARG" && strlength=$OPTARG;;`

right ?

**Comment by jsarenik** [comment]
> Just reading the code and not actually testing but, @jsarenik
> <img alt="image" width="556" src="https://user-images.githubusercontent.com/836049/62320910-5b85c480-b499-11e9-96cb-de46bef459d4.png">
> I think you meant :
> 
> ` L) test -n "$OPTARG" && strlength=$OPTARG;;`
> 
> right ?

Good catch! Thank you @jcbf !

**Comment by jcbf** [comment]
Just a heads-up. 

Also while looking ate cloudflare and route53 documentation,  cloudflare doesn't seem to support records bigger than 255 chars.
https://api.cloudflare.com/#zone-purge-files-by-cache-tags-or-host

> 1073 | Invalid TXT record. Must be less than 255 characters

Route53 seems to be OK.

Not sure if this should be handled with a warning or fail.

**Comment by jsarenik** [comment]
@jcbf thanks! Addressed in latest commit (88c6157f98a6ab50d5c521f66eb2ae41b345bc55). https://api.cloudflare.com/#dns-records-for-a-zone-export-dns-records

**Comment by jsarenik** [comment]
http://makeapullrequest.com/

**Comment by matteocorti** [comment]
Hi, any reason why the option was never merged in the main branch?

**Comment by jsarenik** [comment]
@matteocorti https://github.com/spf-tools/spf-tools/issues/159#issuecomment-517357230 - I hoped for the author of the patch to claim its authorship (and maybe do some extra git, which I hoped will be helpful). But I may be the bottle-neck here, so let me merge now.

**Comment by jsarenik** [comment]
@matteocorti Thanks for heads-up! Closing this issue, re-open if needed.

**Comment by matteocorti** [comment]
Thanks!
