### ISSUE TITLE
Simplify download install and setup instructions

### ISSUE THREAD

**Issue by dominicraf** [spf-tools/spf-tools#162]
For those of us who aren't familiar with git and just want to use these scripts, please provide some simple instructions for how to install them.

**Comment by jsarenik** [comment]
Hi @dominicraf! I totally understand what you mean. Let me first draft something here and according to your feed-back it may later go to the main documentation.

Nevertheless, all this has to be done in the terminal window. There is no GUI to spf-tools yet as far as I know.

 1. Download last release from https://github.com/spf-tools/spf-tools/releases
 1. Extract the downloaded file (either `zip` or `tar.gz`) and enter the extracted directory
 1. Run `./despf.sh <SPF_ENABLED_DOMAIN>` to get a disassembled list of all the ip4/ip6 records in your SPF including chained records
 1. Run `./despf.sh <SPF_ENABLED_DOMAIN> | ./simplify.sh | ./normalize.sh | ./mkblocks.sh <TARGET_DOMAIN> | ./mkzoneent.sh` to get BIND-like zone entries of "flattened" DNS records for  `<SPF_ENABLED_DOMAIN>` whereas the resulting records will be for the `<TARGET_DOMAIN>` (though it is very easy to change `<TARGET_DOMAIN>` at any point, also once you already have the zone lines)

Does this help? I understand that the process is pretty manual, but the point in making these SPF-tools was to encourage understanding of the topic.

Would a `one-wrapper-script-does-it-all` help?

What are your expected results? When you found SPF-tools you had to have some questions in your mind and maybe some expectations regarding what you will find. Please write here the questions and your expectations of the tool that would help you solve your particular situation.

Thank you!

**Comment by dominicraf** [comment]
Thanks for the quick and helpful response, yes that was enough for me, I don't need a GUI! The context is that I am installing postwhite which uses despf.sh. It's all working well now, thanks.

**Comment by jsarenik** [comment]
You are welcome. I am very happy it works for you.

**Comment by jsarenik** [comment]
@dominicraf Closing this issue now. Feelfree to reopen if needed.
