### ISSUE TITLE
Prevent overwrite of other TXT records

### ISSUE THREAD

**Issue by edhgoose** [spf-tools/spf-tools#163]
We're on AWS and we're using route53 for our DNS. We have an SPF and a Google Site Verification TXT record.

When we run `./despf.sh | ./simplify.sh | ./mkblocks.sh | ./route53.sh <our zone id>` we find the google-site-verification TXT record is removed.

Unfortunately, Google requires it to be in place - it seems to check it regularly.

I've fudged it manually in the short term by adding the following to route53.sh, but it's definitely a hack! Can anyone think of a better way of achieving this?

`CHANGES=$(echo $CHANGES | jq -r '.Changes[0].ResourceRecordSet.ResourceRecords += [{"Value": "\"google-site-verification=the-code-from-google\""}]')`

Thanks for building this tool - it's been helpful for us.

**Comment by AlexCline** [comment]
The way I've done this in the past is to use a static SPF TXT record on the root domain that never changes. This record points to a subdomain that contains the TXT record that spf-tools continuously updates. For example:

`example.com. 1200 IN TXT "v=spf1 include:spf1.example.com -all"`
`spf1.example.com. 600 IN TXT "v=spf1 ip4:12.34.56.7 ip4:12.34.56.7 ...snip... include:spf2.example.com -all"`

You lose one lookup hop, but you also don't blow away the other TXT records on the root domain.

If I recall, the UPSERT logic in the AWS CLI is pretty dumb, so it wants to just blow everything away. I haven't tried applying a routing weight or setID to try to narrow down the record to be changed. Might give that a try too.

**Comment by jsarenik** [comment]
Hi @edhgoose ! Thank you for using spf-tools and I am happy you find it useful.

I do not have access to route53 to test, but I trust you on this. Please send a pull-request and I will be happy to merge it in if no one objects - mainly the original author who contributed `route53.sh`... (I mean @AlexClineBB == @AlexCline, later documentation fix by @gglockner).

Thank you all!

**Comment by DanielWeigl** [comment]
Seems to be the same problem with the cloudflare script -> i solved it that way https://github.com/spf-tools/spf-tools/pull/167

**Comment by jcbf** [comment]
I was reviewing this and set up a testing domain on AWS/route53.

Initially, I've implemented a "-a" switch an/ord an env variable to allow to specify additional TXT record using @DanielWeigl idea.
After, I realized that multiple arguments will be nice but for that, the best way to do it is using bash arrays.

@jsarenik , what do you think ?

**Comment by jsarenik** [comment]
@jcbf Generally I am against using any bashisms, simply because some users run SPF-tools on plain *BSD which has another POSIX shell. Sorry for late reply.

**Comment by jsarenik** [comment]
@jcbf Is it possible to achieve what you would need bash arrays for but just with [POSIX shell](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html)?

**Comment by jcbf** [comment]
Probably... I've just coded with arrays before realizing it's a bash only.
Let me look into it and leave it for you to  comment

**Comment by jcbf** [comment]
I committed my WIP code in travis branch. It should be implemented in #170

**Comment by jcbf** [comment]
@edhgoose This works for you?
Instead of keeping the non-SPF records, you must specify them.

**Comment by edhgoose** [comment]
@jcbf perfectly. We've rolled this out into production. Thank you so much for doing this!
