### ISSUE TITLE
Not sure where to post this

### ISSUE THREAD

**Issue by tazboyz16** [spf-tools/spf-tools#181]
https://dmarcian.com/spf-survey/?domain=spf-orig.spf-tools.eu.org
 
Shows that you currently have a broken SPF record due to one of the IPv6 ranges does not have the SPF ip6 flag on it 

v=spf1 ip4:178.40.0.0/15 ip6:2001:470:6e:200::/64 2001:470:6f:200::/64 include:mailgun.org include:_spf.google.com ~all

2001:470:6f:200::/64 is the "breaking" record

**Comment by jsarenik** [comment]
Thank you @tazboyz16 ! Fixed. It was a manually added record from which the rest was generated. Those records are mainly used for testing.
