### ISSUE TITLE
despf.sh google.com gives no output

### ISSUE THREAD

**Issue by blackhold** [spf-tools/spf-tools#182]
Hello,
I just have installed a server using modoboa and following the problem, I passed to postwhite that gived me to spf-tools. I found that /usr/local/bin/spf-tools/despf.sh google.com gives no output. Also I tried to use the cloned version of this repo and continues showing any output.

```
root@mail-2022:/usr/local/bin/spf-tools# ./despf.sh google.com
root@mail-2022:/usr/local/bin/spf-tools# ping -c 1 google.com
PING google.com(par21s05-in-x0e.1e100.net (2a00:1450:4007:812::200e)) 56 data bytes
64 bytes from par21s05-in-x0e.1e100.net (2a00:1450:4007:812::200e): icmp_seq=1 ttl=114 time=6.07 ms

--- google.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 6.071/6.071/6.071/0.000 ms
```

I'm using debian 11.3 inside an ovh cloud server. I have an other lxc server inside proxmox with debian 10.11 and despf.sh gives output.

I checked that a ping resolves to google, also I tried to change de DNS nameserver.

Any clue about what could happen?

Thanks you much

**Comment by blackhold** [comment]
Found the problem: bind9-host was not installed

# apt -y install bind9-host

**Comment by jsarenik** [comment]
I'm happy you solved it. The script should end with an error in the beginning if the `host` command is not available.

```
$ ./despf.sh google.com
$ echo $?
127
```

Hmm. A warning should be added...

**Comment by jsarenik** [comment]
Now it says this:

```
$ ./despf.sh google.com                  
Command `host` is missing. Exiting.
```

Thank you for reporting!

**Comment by blackhold** [comment]
Thanks you much for fixing it! ;) just installed a new modoboa installation and seems it is working (due bind9-host is installed) :)

**Comment by jsarenik** [comment]
@blackhold You are welcome! Thanks again for reporting it. I thought it was already handled so it was good that this issue triggered me to really do it.
